# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batting',
            name='match',
        ),
        migrations.RemoveField(
            model_name='batting',
            name='player',
        ),
        migrations.RemoveField(
            model_name='bowling',
            name='match',
        ),
        migrations.RemoveField(
            model_name='bowling',
            name='player',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='fielding',
            name='match',
        ),
        migrations.RemoveField(
            model_name='fielding',
            name='player',
        ),
        migrations.RemoveField(
            model_name='league',
            name='match',
        ),
        migrations.RemoveField(
            model_name='league',
            name='user',
        ),
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='point',
            name='match',
        ),
        migrations.RemoveField(
            model_name='point',
            name='player',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='league',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='player',
        ),
        migrations.DeleteModel(
            name='Batting',
        ),
        migrations.DeleteModel(
            name='Bowling',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Fielding',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserTeam',
        ),
    ]
