# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=b'', max_length=200, verbose_name=b'Phone Number'),
        ),
    ]
