# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20170619_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[(b'LM', b'League Match'), (b'QF', b'Quarter Final'), (b'SF', b'Semi Final'), (b'FM', b'Final')], default=b'LM', max_length=2),
        ),
    ]
